create table customer (
	customer_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	birth_date DATE,
	phone VARCHAR(50),
	address TEXT,
	city VARCHAR(10),
	state VARCHAR(6),
	points INT
);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (1, 'Aurelie', 'Kopelman', '2023-01-05', '676-840-3243', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Rawalpindi', 'Punjab', 679);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (2, 'Chantalle', 'Bischop', '2023-11-22', '726-202-3722', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 'Kohat', 'Punjab', 552);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (3, 'Solly', 'Adderley', '2023-03-08', '685-560-3894', 'Phasellus id sapien in sapien iaculis congue.', 'Rawalpindi', 'KPK', 1015);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (4, 'Margit', 'Geoghegan', '2023-06-02', '310-313-7113', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'Kohat', 'KPK', 987);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (5, 'Blake', 'Betteridge', '2023-10-13', '253-719-4571', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Kohat', 'Punjab', 1927);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (6, 'Jillene', 'Vernalls', '2023-05-14', '202-735-3287', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Karachi', 'Sindh', 1501);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (7, 'Delano', 'Lovegrove', '2023-10-17', '607-203-1031', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Rawalpindi', 'KPK', 1322);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (8, 'Drake', 'Pochon', '2023-10-06', '975-428-8931', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 'Karachi', 'Punjab', 995);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (9, 'Kathryn', 'Neesam', '2023-08-07', '672-617-0654', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Islamabad', 'KPK', 1789);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (10, 'Sandor', 'Mendus', '2023-02-06', '477-123-8276', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'Kohat', 'Sindh', 1877);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (11, 'Burnaby', 'Petrak', '2023-03-11', '668-589-8126', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'Peshawar', 'KPK', 279);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (12, 'Kamila', 'Rodolico', '2023-05-25', '774-893-7007', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'Rawalpindi', 'Punjab', 1430);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (13, 'Shelbi', 'Robatham', '2023-05-11', '772-587-4332', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Kohat', 'Sindh', 823);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (14, 'Maura', 'Atling', '2023-09-06', '319-772-8471', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Rawalpindi', 'Punjab', 1706);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (15, 'Tabatha', 'Eliez', '2023-10-08', '389-236-2929', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'Peshawar', 'KPK', 981);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (16, 'Booth', 'Tallow', '2023-09-07', '921-524-4927', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'Rawalpindi', 'KPK', 418);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (17, 'Knox', 'Merfin', '2023-10-29', '969-224-2328', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'Karachi', 'Sindh', 548);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (18, 'Alister', 'Dowdle', '2023-06-25', '795-230-2547', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Islamabad', 'Punjab', 282);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (19, 'Aaren', 'Emmanuel', '2023-01-01', '482-866-4661', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'Islamabad', 'Punjab', 1439);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (20, 'Marietta', 'Arnley', '2023-01-11', '597-852-1410', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Islamabad', 'Punjab', 1369);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (21, 'Demott', 'Di Pietro', '2023-04-15', '214-522-5819', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Rawalpindi', 'Galgit', 1658);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (22, 'Victor', 'Binny', '2023-03-17', '751-270-8949', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Peshawar', 'Sindh', 281);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (23, 'Alfi', 'Killimister', '2023-01-12', '421-629-7658', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'Peshawar', 'Galgit', 1495);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (24, 'Willy', 'Gue', '2023-06-01', '713-690-2863', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Rawalpindi', 'KPK', 1000);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (25, 'Georgianne', 'Webben', '2023-02-23', '127-657-5092', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Karachi', 'Punjab', 183);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (26, 'Christiane', 'Summersett', '2023-08-15', '802-861-4185', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Kohat', 'Sindh', 1435);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (27, 'Myrvyn', 'Postlewhite', '2023-06-09', '325-356-3523', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'Kohat', 'Galgit', 998);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (28, 'Robbie', 'Burrell', '2023-04-10', '792-620-5818', 'Quisque id justo sit amet sapien dignissim vestibulum.', 'Islamabad', 'KPK', 414);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (29, 'Kristi', 'Blanpein', '2023-05-07', '521-408-0270', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Islamabad', 'Sindh', 1933);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (30, 'Northrup', 'Salkild', '2023-06-02', '466-862-8716', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'Peshawar', 'KPK', 1024);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (31, 'Timmie', 'Anderson', '2023-03-27', '595-940-4268', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'Peshawar', 'Punjab', 1566);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (32, 'Nannie', 'Loos', '2023-06-10', '150-764-6925', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'Peshawar', 'Galgit', 253);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (33, 'Ashlin', 'Ericssen', '2023-01-31', '948-333-6271', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'Kohat', 'Punjab', 1476);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (34, 'Colly', 'Hawket', '2023-04-06', '560-361-3987', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Karachi', 'Galgit', 1848);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (35, 'Leese', 'Dumpleton', '2023-11-30', '415-778-9019', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Islamabad', 'Sindh', 1831);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (36, 'Ab', 'Olander', '2023-09-04', '149-594-3015', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'Karachi', 'Punjab', 975);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (37, 'Bria', 'McCraw', '2023-02-10', '807-688-4730', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Kohat', 'Galgit', 271);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (38, 'Howard', 'Mound', '2023-11-10', '470-737-0175', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 'Kohat', 'KPK', 719);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (39, 'Rivi', 'Beedham', '2023-10-25', '923-209-8952', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'Karachi', 'Galgit', 1505);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (40, 'Serene', 'Johnsee', '2023-02-02', '608-625-8908', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'Kohat', 'KPK', 662);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (41, 'Mickie', 'Le Merchant', '2023-10-19', '648-429-1591', 'Maecenas pulvinar lobortis est.', 'Peshawar', 'KPK', 316);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (42, 'Hedy', 'Nelthrop', '2023-12-16', '796-502-6769', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Islamabad', 'Galgit', 441);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (43, 'Micaela', 'Fasson', '2023-04-29', '644-950-8775', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Karachi', 'Sindh', 253);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (44, 'Dwayne', 'Crigin', '2023-12-20', '270-296-7483', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 'Rawalpindi', 'Sindh', 1392);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (45, 'Anthe', 'Fullicks', '2023-07-13', '582-224-9948', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Karachi', 'KPK', 547);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (46, 'Ogdon', 'Wheal', '2023-04-11', '763-952-5394', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'Karachi', 'Sindh', 1275);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (47, 'Magdalene', 'Mapes', '2023-10-31', '150-239-8613', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 'Kohat', 'Punjab', 1312);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (48, 'Nell', 'Querree', '2023-02-18', '417-643-3546', 'Maecenas pulvinar lobortis est.', 'Karachi', 'Punjab', 392);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (49, 'Traver', 'Brikner', '2023-11-21', '523-506-8549', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'Karachi', 'Galgit', 1408);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state, points) values (50, 'Randie', 'Livoir', '2023-10-28', '807-823-3606', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'Karachi', 'Sindh', 1357);
