create table customer (
	customer_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	birth_date DATE,
	phone VARCHAR(50),
	address TEXT,
	city VARCHAR(10),
	state VARCHAR(6)
);
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (1, 'Vinny', 'Brewin', '2023-05-06', '989-575-0437', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'Rawalpindi', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (2, 'Zack', 'MacAless', '2023-08-17', '217-294-4773', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'Peshawar', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (3, 'Aland', 'Bernardoni', '2023-02-25', '312-426-1109', 'In hac habitasse platea dictumst.', 'Islamabad', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (4, 'Jeanine', 'Kiln', '2023-09-20', '605-963-8520', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Karachi', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (5, 'Windy', 'McKirdy', '2023-11-24', '921-967-8138', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Karachi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (6, 'Bernardo', 'Thistleton', '2023-12-03', '124-890-3943', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Peshawar', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (7, 'Yasmin', 'Sturrock', '2023-07-03', '155-745-2120', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Rawalpindi', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (8, 'Paul', 'Ness', '2023-10-13', '897-566-5067', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'Kohat', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (9, 'Iseabal', 'Janny', '2023-01-14', '895-272-0941', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'Rawalpindi', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (10, 'Costa', 'Jagoe', '2023-08-04', '312-374-9987', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Islamabad', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (11, 'Mordy', 'Bullard', '2023-03-14', '109-383-1543', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 'Karachi', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (12, 'Agnes', 'Zelake', '2023-04-26', '500-144-7732', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'Karachi', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (13, 'Curr', 'Bywater', '2023-06-01', '950-552-7994', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Islamabad', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (14, 'Brietta', 'Beveredge', '2023-10-23', '240-994-2592', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'Kohat', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (15, 'Merell', 'Snipe', '2023-10-15', '577-598-3615', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Peshawar', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (16, 'Hort', 'McQuilkin', '2023-07-03', '646-993-0543', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Karachi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (17, 'Emili', 'de Clercq', '2023-06-30', '625-821-4547', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'Kohat', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (18, 'Alethea', 'Killbey', '2023-06-06', '533-276-8018', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Islamabad', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (19, 'Ulises', 'Duchan', '2023-06-11', '158-894-3114', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Rawalpindi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (20, 'Maud', 'Calven', '2023-01-25', '578-309-3549', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Kohat', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (21, 'Jasmina', 'Gorton', '2023-12-07', '451-861-9584', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'Karachi', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (22, 'Kayla', 'Cowterd', '2023-08-19', '843-402-9512', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 'Kohat', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (23, 'Timothy', 'Waddoups', '2023-02-26', '153-977-5644', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Karachi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (24, 'Iggy', 'Petri', '2023-04-11', '822-125-9741', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 'Kohat', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (25, 'Betta', 'Penrice', '2023-08-10', '296-754-7244', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'Karachi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (26, 'Sara', 'Ashplant', '2023-02-09', '273-851-5662', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Islamabad', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (27, 'Cordie', 'Spoerl', '2023-10-14', '428-516-5907', 'Nullam porttitor lacus at turpis.', 'Karachi', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (28, 'Lynn', 'McNae', '2023-02-23', '198-257-9753', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Rawalpindi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (29, 'Ethe', 'Quogan', '2023-03-15', '492-719-7978', 'Cras non velit nec nisi vulputate nonummy.', 'Islamabad', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (30, 'Gizela', 'Whitwood', '2023-10-06', '835-771-6388', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Islamabad', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (31, 'Josi', 'Rodgier', '2023-06-03', '962-396-4926', 'Ut tellus.', 'Kohat', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (32, 'Lorene', 'Fernant', '2023-05-27', '652-213-9935', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Islamabad', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (33, 'Vonnie', 'Sutherns', '2023-10-16', '735-627-9416', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Peshawar', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (34, 'Lauren', 'Menego', '2023-07-25', '726-874-9160', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'Kohat', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (35, 'Mirabelle', 'Foulkes', '2023-12-17', '430-801-1023', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Kohat', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (36, 'Cele', 'Mulderrig', '2023-08-23', '941-456-4503', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Rawalpindi', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (37, 'Waylen', 'Shakelade', '2023-08-22', '641-936-7740', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Kohat', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (38, 'Geri', 'Jenne', '2023-05-01', '709-840-4948', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Rawalpindi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (39, 'Carla', 'Purviss', '2023-03-29', '628-538-3434', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 'Karachi', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (40, 'Svend', 'Ginley', '2023-04-07', '864-698-5541', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', 'Islamabad', 'Punjab');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (41, 'Karilynn', 'Chene', '2023-12-17', '964-143-1585', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Islamabad', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (42, 'Chaddy', 'Sudell', '2023-11-28', '258-839-9674', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 'Rawalpindi', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (43, 'Svend', 'Padbery', '2023-11-19', '848-535-8183', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 'Peshawar', 'Sindh');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (44, 'Maison', 'Bingell', '2023-06-14', '136-155-8725', 'Ut tellus.', 'Kohat', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (45, 'Doris', 'Cund', '2023-03-01', '290-140-1942', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Rawalpindi', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (46, 'Lenore', 'Grinley', '2023-07-05', '973-182-1596', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Rawalpindi', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (47, 'Carmen', 'Rein', '2023-03-10', '924-439-2482', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'Karachi', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (48, 'Etheline', 'Glassup', '2023-01-25', '103-813-1258', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Kohat', 'KPK');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (49, 'Jeth', 'Elder', '2023-05-28', '265-341-6415', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Peshawar', 'Galgit');
insert into customer (customer_id, first_name, last_name, birth_date, phone, address, city, state) values (50, 'Rina', 'Abbys', '2023-01-27', '844-904-6599', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Peshawar', 'Punjab');
