insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33392, 'Régine', 'Rubinek', 'Systems Administrator IV', '$8.20', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33393, 'Maïwenn', 'Jobke', 'Geological Engineer', '$8.59', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33394, 'Noémie', 'Ximenez', 'Engineer I', '$5.35', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33395, 'Pélagie', 'Riddiough', 'Recruiter', '$7.41', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33396, 'Maïly', 'Mixon', 'Technical Writer', '$3.73', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33397, 'Adélaïde', 'Jillett', 'Research Associate', '$9.98', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33398, 'Cinéma', 'Priestman', 'Structural Analysis Engineer', '$5.60', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33399, 'Marie-hélène', 'Donisthorpe', 'Associate Professor', '$7.52', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33400, 'Pénélope', 'Essel', 'Staff Accountant I', '$8.44', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33401, 'Lauréna', 'Benger', 'Help Desk Operator', '$3.81', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33402, 'Cécile', 'Edwinson', 'Tax Accountant', '$7.01', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33403, 'Anaïs', 'Weson', 'Account Representative III', '$2.55', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33404, 'Clélia', 'Weddeburn', 'Compensation Analyst', '$2.23', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33405, 'Sòng', 'Blincowe', 'Electrical Engineer', '$0.89', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33406, 'Börje', 'Hamson', 'Graphic Designer', '$7.13', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33407, 'Annotée', 'Belcher', 'Technical Writer', '$5.70', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33408, 'Yénora', 'Christofides', 'Actuary', '$0.31', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33409, 'Renée', 'Coleshill', 'Automation Specialist I', '$9.50', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33410, 'Maëline', 'Piburn', 'Recruiting Manager', '$7.85', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33411, 'Yáo', 'Blease', 'Human Resources Assistant I', '$10.00', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33412, 'Yénora', 'Pennicard', 'Geological Engineer', '$5.92', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33413, 'Cécile', 'Crumbleholme', 'Human Resources Assistant I', '$7.50', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33414, 'Bérénice', 'Scimoni', 'Programmer Analyst II', '$0.83', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33415, 'Styrbjörn', 'MacCole', 'Senior Developer', '$9.00', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33416, 'Estève', 'Yuryshev', 'Administrative Assistant IV', '$1.55', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33417, 'Léone', 'Gadsby', 'Associate Professor', '$4.95', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33418, 'Marie-hélène', 'Casement', 'Biostatistician IV', '$1.11', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33419, 'Loïc', 'Jedraszczyk', 'Account Coordinator', '$2.66', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33420, 'Adèle', 'O''Mullally', 'Biostatistician III', '$8.62', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33421, 'Eugénie', 'Brecknock', 'Analyst Programmer', '$5.69', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33422, 'Gaétane', 'Hunnywell', 'Registered Nurse', '$8.65', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33423, 'Gaïa', 'Jerwood', 'Human Resources Manager', '$8.03', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33424, 'Léone', 'Smuth', 'Pharmacist', '$6.76', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33425, 'Lén', 'Colly', 'Mechanical Systems Engineer', '$5.05', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33426, 'Yáo', 'Wardhaw', 'Environmental Tech', '$9.46', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33427, 'Andréanne', 'Gately', 'Statistician III', '$5.90', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33428, 'Almérinda', 'Logsdale', 'Paralegal', '$4.26', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33429, 'Åslög', 'Gramer', 'Environmental Tech', '$3.59', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33430, 'Cinéma', 'Michelmore', 'Systems Administrator I', '$2.05', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33431, 'Desirée', 'Grellier', 'Actuary', '$2.57', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33432, 'Pénélope', 'Ulyat', 'Senior Sales Associate', '$3.49', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33433, 'Anaé', 'Hasselby', 'Legal Assistant', '$0.70', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33434, 'Eliès', 'Crouch', 'Associate Professor', '$5.44', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33435, 'Lyséa', 'Dunphy', 'Technical Writer', '$3.66', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33436, 'Réjane', 'Bemrose', 'Software Engineer I', '$3.26', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33437, 'Kévina', 'Briskey', 'Budget/Accounting Analyst I', '$0.40', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33438, 'Kù', 'Adolthine', 'Social Worker', '$6.52', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33439, 'Mélodie', 'Strangman', 'VP Quality Control', '$5.44', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33440, 'Réjane', 'Blackford', 'Physical Therapy Assistant', '$1.92', 33391, 10);
insert into employees (employee_id, first_name, last_name, job_title, salary, reports_to, offic_id) values (33441, 'Marylène', 'Toovey', 'GIS Technical Architect', '$4.81', 33391, 10);
