create table products (
	product_id INT,
	name VARCHAR(50),
	quantity VARCHAR(50)
);
insert into products (product_id, name, quantity) values (1, 'Beef - Ground, Extra Lean, Fresh', '30');
insert into products (product_id, name, quantity) values (2, 'Nantucket Pine Orangebanana', '10');
insert into products (product_id, name, quantity) values (3, 'Mustard - Seed', '30');
insert into products (product_id, name, quantity) values (4, 'Chocolate - Unsweetened', '10');
insert into products (product_id, name, quantity) values (5, 'Sauce - Soy Low Sodium - 3.87l', '20');
insert into products (product_id, name, quantity) values (6, 'Raspberries - Frozen', '20');
insert into products (product_id, name, quantity) values (7, 'Compound - Raspberry', '30');
insert into products (product_id, name, quantity) values (8, 'Pasta - Elbows, Macaroni, Dry', '30');
insert into products (product_id, name, quantity) values (9, 'Cream - 10%', '30');
insert into products (product_id, name, quantity) values (10, 'Fond - Neutral', '10');
insert into products (product_id, name, quantity) values (11, 'Parasol Pick Stir Stick', '40');
insert into products (product_id, name, quantity) values (12, 'Raisin - Golden', '30');
insert into products (product_id, name, quantity) values (13, 'Cheese - Swiss', '20');
insert into products (product_id, name, quantity) values (14, 'Isomalt', '10');
insert into products (product_id, name, quantity) values (15, 'Soup - Campbells Tomato Ravioli', '20');
insert into products (product_id, name, quantity) values (16, 'Vanilla Beans', '10');
insert into products (product_id, name, quantity) values (17, 'Oysters - Smoked', '10');
insert into products (product_id, name, quantity) values (18, 'Flower - Daisies', '10');
insert into products (product_id, name, quantity) values (19, 'Lid - 0090 Clear', '30');
insert into products (product_id, name, quantity) values (20, 'Chinese Foods - Chicken Wing', '10');
insert into products (product_id, name, quantity) values (21, 'Glycerine', '10');
insert into products (product_id, name, quantity) values (22, 'Bread - French Baquette', '10');
insert into products (product_id, name, quantity) values (23, 'Yeast Dry - Fermipan', '30');
insert into products (product_id, name, quantity) values (24, 'Wine - Dubouef Macon - Villages', '40');
insert into products (product_id, name, quantity) values (25, 'Soup - French Onion', '20');
insert into products (product_id, name, quantity) values (26, 'Shallots', '10');
insert into products (product_id, name, quantity) values (27, 'French Pastries', '20');
insert into products (product_id, name, quantity) values (28, 'Jam - Apricot', '30');
insert into products (product_id, name, quantity) values (29, 'Juice - V8, Tomato', '20');
insert into products (product_id, name, quantity) values (30, 'Coffee Caramel Biscotti', '10');
insert into products (product_id, name, quantity) values (31, 'Bonito Flakes - Toku Katsuo', '20');
insert into products (product_id, name, quantity) values (32, 'Doilies - 7, Paper', '10');
insert into products (product_id, name, quantity) values (33, 'Anchovy Fillets', '40');
insert into products (product_id, name, quantity) values (34, 'Wine - Cahors Ac 2000, Clos', '30');
insert into products (product_id, name, quantity) values (35, 'Nut - Pumpkin Seeds', '30');
insert into products (product_id, name, quantity) values (36, 'Steampan - Foil', '40');
insert into products (product_id, name, quantity) values (37, 'Chinese Foods - Chicken', '40');
insert into products (product_id, name, quantity) values (38, 'Orange - Tangerine', '20');
insert into products (product_id, name, quantity) values (39, 'Amarula Cream', '30');
insert into products (product_id, name, quantity) values (40, 'Wine - Barossa Valley Estate', '20');
insert into products (product_id, name, quantity) values (41, 'Table Cloth 144x90 White', '10');
insert into products (product_id, name, quantity) values (42, 'Soup - Knorr, Classic Can. Chili', '40');
insert into products (product_id, name, quantity) values (43, 'Tomatoes - Vine Ripe, Yellow', '20');
insert into products (product_id, name, quantity) values (44, 'Flour - So Mix Cake White', '40');
insert into products (product_id, name, quantity) values (45, 'Soup - Beef Conomme, Dry', '20');
insert into products (product_id, name, quantity) values (46, 'Yams', '10');
insert into products (product_id, name, quantity) values (47, 'Wine - Maipo Valle Cabernet', '40');
insert into products (product_id, name, quantity) values (48, 'Beef - Shank', '30');
insert into products (product_id, name, quantity) values (49, 'Cleaner - Bleach', '30');
insert into products (product_id, name, quantity) values (50, 'Wine - Red, Cabernet Merlot', '30');
